# Generated by Django 6.0.5 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('turno_origen', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('color_alerta', models.CharField(choices=[('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('AZUL', 'Azul'), ('FUCSIA', 'Fucsia'), ('BLANCO', 'Blanco')], max_length=20)),
                ('personal_a_cargo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('leido', models.BooleanField(default=False)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
