# Generated by Django 5.2.1 on 2026-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0003_recado_fields_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recado',
            name='color_alerta',
        ),
        migrations.RemoveField(
            model_name='recado',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='recado',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='recado',
            name='personal_a_cargo',
        ),
        migrations.RemoveField(
            model_name='recado',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='recado',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recado',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='recado',
            name='turno_origen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
