# Generated by Django 6.0.5 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('madrugada', 'Madrugada')], max_length=20)),
                ('fecha_apertura', models.DateField()),
                ('hora_apertura', models.TimeField()),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('DEUDA', 'Deuda')], max_length=20)),
                ('tipo_caja', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('modulo', models.CharField(choices=[('HOTEL', 'Hotel'), ('MARKET', 'Market'), ('COCHERA', 'Cochera'), ('ADICIONAL', 'Adicional'), ('OTRO', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
