# Generated by Django 6.0.5 on 2026-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
