# Generated by Django 5.2.1 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_bloqueado_movimientocaja_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('madrugada', 'Madrugada')], max_length=20),
        ),
    ]
