# Generated by Django 6.0.5 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioCochera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('BUS', 'Bus')], max_length=10)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado')], default='LIBRE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('placa', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('nombre_conductor', models.CharField(max_length=150)),
                ('dni_conductor', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo_cliente', models.CharField(choices=[('PUBLICO', 'Público'), ('HUESPED', 'Huésped')], max_length=20)),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('tarifa_tipo', models.CharField(choices=[('POR_HORA', 'Por hora'), ('FRACCION', 'Fracción'), ('DIA_COMPLETO', 'Día completo'), ('NOCTURNA', 'Nocturna')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
