# Generated by Django 6.0.5 on 2026-05-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cochera', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovehiculo',
            name='checkin_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='hotel.checkin'),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='cochera.espaciocochera'),
        ),
    ]
