# Generated by Django 5.2.1 on 2026-08-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cochera', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovehiculo',
            name='hora_salida_estimada',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registrovehiculo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
