# Generated by Django 6.0.5 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('fecha_salida_estimada', models.DateField(blank=True, null=True)),
                ('hora_salida_estimada', models.TimeField(blank=True, null=True)),
                ('fecha_salida_real', models.DateField(blank=True, null=True)),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('turno_ingreso', models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche'), ('MADRUGADA', 'Madrugada')], max_length=20)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('RESERVA', 'Reserva')], default='ACTIVO', max_length=20)),
                ('es_pareja', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subtotal_habitacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_market', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_cochera', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta'), ('MIXTO', 'Mixto')], max_length=20)),
                ('deuda_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('piso', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('SUITE', 'Suite'), ('MATRI', 'Matri'), ('MATRI_VIP', 'Matri Vip'), ('BLUE', 'Blue'), ('RED', 'Red'), ('TRIPLE', 'Triple'), ('CAFETIN', 'Cafetín')], max_length=20)),
                ('marca_tv', models.CharField(choices=[('JVC', 'JVC'), ('JVC_V', 'JVC V'), ('HISENSE', 'Hisense'), ('SM', 'SM')], max_length=20)),
                ('tipo_cama', models.CharField(choices=[('DOS_PLAZAS', 'Dos Plazas'), ('QUEEN', 'Queen'), ('KING', 'King')], max_length=20)),
                ('estado_ocupacion', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('estado_limpieza', models.CharField(choices=[('LIMPIO', 'Limpio'), ('SUCIO', 'Sucio')], default='LIMPIO', max_length=20)),
                ('tarifa_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_madrugada', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni_pasaporte', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ciudad_origen', models.CharField(blank=True, max_length=100)),
                ('nacionalidad', models.CharField(choices=[('PERU', 'Peru'), ('EXTRANJERO', 'Extranjero')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('PAREJA', 'Pareja'), ('CASADO', 'Casado')], max_length=20)),
                ('tipo_visita', models.CharField(choices=[('INDEPENDIENTE', 'Independiente'), ('VIAJERO', 'Viajero'), ('TURISTA', 'Turista')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_llegada_estimada', models.DateField()),
                ('hora_llegada_estimada', models.TimeField()),
                ('monto_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_pago_adelanto', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('alerta_color', models.CharField(choices=[('ROJO', 'Rojo'), ('AMARILLO', 'Amarillo')], default='AMARILLO', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
