# Generated by Django 6.0.5 on 2026-05-31 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoadicional',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_adicionales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoadicional',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_adicionales', to='hotel.checkin'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='hotel.checkin'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='trabajador_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='hotel.huesped'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitacion_preferida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.huesped'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
