# Generated by Django 5.2.1 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='turno_ingreso',
            field=models.CharField(choices=[('DIA', 'Día'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche'), ('MADRUGADA', 'Madrugada')], max_length=20),
        ),
    ]
