# Generated by Django 5.2.16 on 2026-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_checkin_turno_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_garantia',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA_CHECKIN', 'Confirmada (Check-in)'), ('VENCIDA_REEMBOLSO', 'Vencida / Reembolso'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
