# Generated by Django 5.2.16 on 2026-07-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reserva_monto_garantia_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_from_reserva', to='hotel.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA_CHECKIN', 'Confirmada (Check-in)'), ('COMPLETADA', 'Completada'), ('VENCIDA_REEMBOLSO', 'Vencida / Reembolso'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
