# Generated by Django 6.0.5 on 2026-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('SNACK', 'Snack'), ('BEBIDA', 'Bebida'), ('HIGIENE', 'Higiene'), ('CHICLE', 'Chicle'), ('CARAMELO', 'Caramelo'), ('GALLETA', 'Galleta'), ('PRESERVATIVO', 'Preservativo'), ('CUBIERTOS', 'Cubiertos'), ('VASITOS', 'Vasitos')], max_length=30)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('tipo_registro', models.CharField(choices=[('EXHIBICION', 'Exhibición'), ('STOCK', 'Stock')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VentaMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo_venta', models.CharField(choices=[('DIRECTO', 'Directo'), ('CARGADO_HABITACION', 'Cargado a habitación')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
