# Generated by Django 5.2.1 on 2026-08-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_registro',
        ),
    ]
