# Generated by Django 5.2.1 on 2026-08-29 00:00

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_eliminar_stock_ambiguo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('ALMACEN', 'Almacén'), ('RECEPCION', 'Recepción'), ('REFRIGERADORA', 'Refrigeradora')], max_length=20, verbose_name='origen')),
                ('destino', models.CharField(choices=[('ALMACEN', 'Almacén'), ('RECEPCION', 'Recepción'), ('REFRIGERADORA', 'Refrigeradora')], max_length=20, verbose_name='destino')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='market.producto', verbose_name='producto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='trabajador')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'transferencia de stock',
                'verbose_name_plural': 'transferencias de stock',
            },
        ),
    ]