# Generated by Django 5.2.16 on 2026-08-29 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_stock_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destino',
            field=models.CharField(choices=[('ALMACEN', 'Almacén'), ('RECEPCION', 'Recepción'), ('REFRIGERADORA', 'Refrigeradora')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='origen',
            field=models.CharField(choices=[('ALMACEN', 'Almacén'), ('RECEPCION', 'Recepción'), ('REFRIGERADORA', 'Refrigeradora')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='market.producto'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
